[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = "-C link-arg=-Ttests/link.lds"
runner = "qemu-system-riscv64 -smp 4 -m 256M -machine virt -nographic -serial mon:stdio -kernel "

[target.riscv32imac-unknown-none-elf]
rustflags = "-C link-arg=-Ttests/link.lds"
runner = "qemu-system-riscv32 -smp 4 -m 256M -machine virt -nographic -serial mon:stdio -kernel "
